#!/usr/bin/env python3
#
#    JKS - Measurement database system
#    Copyright (C) 2013-2024  Christoph Lehner (christoph.lehner@ur.de, https://github.com/lehner/jks)
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
import jks, sys, os, math, glob
if len(sys.argv) < 4:
    print("%s out in tag_pattern_1 [ tag_pattern_2 ... ]" % sys.argv[0])
    sys.exit(0)

fno=sys.argv[1]

res=jks.resamples()
ji=jks.resamples(sys.argv[2])

for f in sys.argv[3:]:
    print("Adding %s" % (f))
    m=ji.match(f)
    if len(m) == 0:
        print("WARNING: no tag matches %s" % f)
    for n in m:
        # a tag matched by several patterns is taken once
        if n not in res.keys():
            res.add(n,ji.get(n))

if len(res.keys()) == 0:
    print("ERROR: no tag of %s matches, %s is not written" % (sys.argv[2],fno))
    sys.exit(1)

res.compress()

res.save(fno)

